export const ActionTypes = {
    SET_EMPLOYEE: 'SET_EMPLOYEE',
    SET_EMPLOYEE_ERROR: 'SET_EMPLOYEE_ERROR',
    SET_EMPLOYEE_LOADING: 'SET_EMPLOYEE_LOADING',
    GET_COMPANIES: 'GET_COMPANIES',
    GET_COMPANIES_LOADING: 'GET_COMPANIES_LOADING',
    GET_COMPANIES_ERROR: 'GET_COMPANIES_ERROR',
    SET_FILTER_ARRAY: 'SET_FILTER_ARRAY',
    SET_STATUS: 'SET_STATUS',
}
